# Use the official PHP 8 image as the base image
FROM php:8.3-fpm

# Set the working directory
WORKDIR /var/www/html

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Write xdebug settings to a separate ini file so the `zend_extension=` line
# generated by docker-php-ext-enable above is preserved (not overwritten).
RUN { \
        echo "xdebug.mode=coverage"; \
        echo "xdebug.start_with_request=yes"; \
        echo "xdebug.client_host=host.docker.internal"; \
        echo "xdebug.client_port=9000"; \
    } > /usr/local/etc/php/conf.d/xdebug-settings.ini

# Install Composer (a PHP package manager)
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

# Mount a local folder to /var/www/html
VOLUME ./:/var/www/html

# Install project dependencies
#RUN composer install --optimize-autoloader --dev

# Set the appropriate file permissions
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Run the PHP-FPM server
CMD ["php-fpm"]
